apiVersion: v1
kind: Service
metadata:
  name: hello-node
spec:
  type: NodePort
  selector:
    app: hello-node
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      nodePort: 31111
